'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { getProducts, addSale } from '@/app/actions/products'
import { useLanguage } from '@/components/language-provider'
import LoadingScreen from '@/components/loading-screen'

type Type = { id: string; variantName: string; size?: string | null; unit: string; currentStock: number; sellingPrice: string; activeStatus: boolean }
type Product = { id: string; name: string; variants: Type[] }
export default function SalesForm() {
  const router = useRouter(); const { t } = useLanguage(); const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [override, setOverride] = useState(false)
  const [data, setData] = useState({ productId: '', variantId: '', quantity: 0, sellingPrice: 0, saleDate: new Date().toISOString().split('T')[0] })
  useEffect(() => { getProducts().then((items) => setProducts(items as Product[])).catch(console.error) }, [])
  const product = products.find((item) => item.id === data.productId); const types = product?.variants.filter((item) => item.activeStatus) ?? []; const type = types.find((item) => item.id === data.variantId)
  useEffect(() => { if (type && !override) setData((current) => ({ ...current, sellingPrice: globalThis.Number(type.sellingPrice) })) }, [type, override])
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); setLoading(true); try { if (!data.productId || !data.variantId) throw new Error(`${t('common.selectProduct')} / ${t('common.selectType')}`); if (data.quantity <= 0 || data.sellingPrice <= 0) throw new Error(t('sales.priceRequired')); if (data.quantity > (type?.currentStock ?? 0)) throw new Error(t('sales.stockRequired')); await addSale({ ...data, quantity: Number(data.quantity), sellingPrice: Number(data.sellingPrice) }); router.push('/') } catch (err) { setError(err instanceof Error ? err.message : t('sales.recordFailed')) } finally { setLoading(false) } }
  return <div className="relative">{loading && <LoadingScreen message={t('sales.recording')} />}<form onSubmit={submit} className="rounded-lg border border-gray-200 bg-white p-6">{error && <div className="mb-4 rounded border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}<Field label={t('common.product')} value={data.productId} disabled={loading} onChange={(value) => { setOverride(false); setData({ ...data, productId: value, variantId: '', sellingPrice: 0 }) }}><option value="">{t('common.selectProduct')}</option>{products.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Field><Field label={t('common.type')} value={data.variantId} disabled={loading || !product} onChange={(value) => { setOverride(false); setData({ ...data, variantId: value, sellingPrice: 0 }) }}><option value="">{t('common.selectType')}</option>{types.map((item) => <option key={item.id} value={item.id}>{item.variantName}{item.size ? ` (${item.size})` : ''}</option>)}</Field>{type && <div className="mb-4 rounded border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">{t('common.available')}: <b>{type.currentStock} {type.unit}</b><br />{t('common.masterPrice')}: <b>₹{type.sellingPrice}</b></div>}<div className="mb-4 grid grid-cols-2 gap-4"><Number label={t('common.quantity')} value={data.quantity} onChange={(value) => setData({ ...data, quantity: value })} /><Number label={t('sales.pricePerUnit')} value={data.sellingPrice} step="0.01" disabled={!override} onChange={(value) => setData({ ...data, sellingPrice: value })} /></div>{type && <label className="mb-4 flex items-center text-sm font-medium"><input type="checkbox" checked={override} onChange={(event) => setOverride(event.target.checked)} className="mr-2" />{t('common.overridePrice')}</label>}{data.quantity > 0 && data.sellingPrice > 0 && <div className="mb-4 rounded border border-green-200 bg-green-50 p-3"><p className="text-sm text-gray-600">{t('common.totalAmount')}</p><p className="text-2xl font-bold text-green-600">₹{(data.quantity * data.sellingPrice).toFixed(2)}</p></div>}<div className="mb-4"><label className="mb-2 block text-sm font-medium">{t('common.date')}</label><input type="date" value={data.saleDate} onChange={(event) => setData({ ...data, saleDate: event.target.value })} className="w-full rounded-lg border border-gray-300 px-4 py-2" /></div><button disabled={loading} className="w-full rounded-lg bg-green-600 px-4 py-3 font-bold text-white">{t('sales.recordButton')}</button><button type="button" onClick={() => router.back()} className="mt-2 w-full rounded-lg bg-gray-200 px-4 py-3">{t('common.cancel')}</button></form></div>
}
function Field({ label, value, disabled, onChange, children }: { label: string; value: string; disabled?: boolean; onChange: (value: string) => void; children: React.ReactNode }) { return <div className="mb-4"><label className="mb-2 block text-sm font-medium">{label}</label><select value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} className="w-full rounded-lg border border-gray-300 px-4 py-2">{children}</select></div> }
function Number({ label, value, disabled, onChange, step }: { label: string; value: number; disabled?: boolean; onChange: (value: number) => void; step?: string }) { return <div><label className="mb-2 block text-sm font-medium">{label}</label><input type="number" min="0" step={step} value={value} disabled={disabled} onChange={(event) => onChange(globalThis.Number(event.target.value) || 0)} className="w-full rounded-lg border border-gray-300 px-4 py-2" /></div> }
